[0m[[0m[0mdebug[0m] [0m[0mRunning TaskDef(demo.AppTests, org.scalatest.tools.Framework$$anon$1@8306530, false, [SuiteSelector])[0m
[0m[[0m[0mdebug[0m] [0m[0mRunning TaskDef(demo.AuthedServiceTests, org.scalatest.tools.Framework$$anon$1@8306530, false, [SuiteSelector])[0m
[0m[[0m[0minfo[0m] [0m[0m[32mAppTests:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test loadConfig[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mAuthedServiceTests:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test loginServiceReturnBoolean[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test loginServiceReturnUser[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test checkNumberFail[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test checkNumberOK[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test Throws an exception[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test doNothong[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- test verify exception error_code_011[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mRun completed in 2 seconds, 270 milliseconds.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mTotal number of tests run: 8[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mSuites: completed 2, aborted 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mTests: succeeded 8, failed 0, canceled 0, ignored 0, pending 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mAll tests passed.[0m[0m
[0m[[0m[0mdebug[0m] [0m[0mPassed tests:[0m
[0m[[0m[0mdebug[0m] [0m[0m	demo.AppTests[0m
[0m[[0m[0mdebug[0m] [0m[0m	demo.AuthedServiceTests[0m
